import type { Metadata } from "next";
import "../globals.css"
import Header from "../components/Landing_Layout/Header/page";
import Footer from "../components/Landing_Layout/Footer/page";

export const metadata: Metadata = {
    title: "Giriş Yap - CraftingAı",
    description: "Generated by create next app",
};

export default function LandingLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {

    return (
        <>
            <Header />

            <main>
                {children}
            </main>

            <Footer />

        </>
    );
}
