import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css"
import Header from "../components/Landing_Layout/Header/page"; 
import Footer from "../components/Landing_Layout/Footer/page"; 

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Landing page",
    description: "Generated by create next app",
};

export default function LandingLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {

    return (
        <html lang="en" className="h-full scroll-smooth">
            <head>
                <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/7.0.1/css/all.min.css" integrity="sha512-2SwdPD6INVrV/lHTZbO2nodKhrnDdJK9/kg2XD1r9uGqPo1cUbujc+IYdlYdEErWNu69gVcYgdxlmVmzTWnetw==" crossOrigin="anonymous" referrerPolicy="no-referrer" />
            </head>
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased h-full bg-gradient-to-r from-slate-900 to-slate-700`} >

                <Header />

                <main>
                    {children}
                </main>

                <Footer />

            </body>
        </html>
    );
}
