import type { Metadata } from "next";
import Header from "@/app/components/Landing_Layout/Header";
import Footer from "@/app/components/Landing_Layout/Footer";

export const metadata: Metadata = {
    title: "Giriş Yap - CraftingAı",
    description: "Generated by create next app",
};

export default function LandingLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {

    return (
        <>
            <Header />

            <main>
                {children}
            </main>

            <Footer />
        </>
    );
}
